apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/nmirasch/downstream-dex?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "GITOPS-6959_build_microshift-gitops_rpm" && ( "rpms/***".pathChanged() ||
      ".tekton/microshift-gitops-rpm-pull-request.yaml".pathChanged() )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: testing-rpms-builds
    appstudio.openshift.io/component: microshift-gitops-rpm
    pipelines.appstudio.openshift.io/type: build
  name: microshift-gitops-rpm-on-push
  namespace: rh-openshift-gitops-tenant
spec:
  pipelineSpec:
    params:
    - name: git-url
    - name: revision
    - name: ociStorage
    - name: argo-cd-url
    - name: redis-url
    - name: source-commit
    - name: source-url
    workspaces:
    - name: source
    - name: git-auth
    
    tasks:
    # TASK1: Clone repository
    - name: fetch-repository
      taskRef: { name: git-clone, kind: ClusterTask }
      workspaces:
      - name: output
        workspace: source
      params:
      - name: url
        value: $(params.git-url)
      - name: revision
        value: $(params.revision)
    
    # TASK 2: Build the docker image to generate the spec file
    - name: build-spec-generator-image
      runAfter: [fetch-repository]
      taskRef: { name: buildah, kind: ClusterTask }
      params:
      - name: IMAGE
        value: "$(params.ociStorage)-spec-generator:{{revision}}"
      - name: DOCKERFILE
        value: rpms/microshift-gitops/Dockerfile
      workspaces:
      - name: source
        workspace: source
    
    # TASK 3: Generate.spec file
    - name: generate-spec-file
      runAfter: [build-spec-generator-image]
      taskSpec:
        params:
        - name: argo-cd-url
        - name: redis-url
        - name: source-commit
        - name: source-url
        - name: generator-image-url
        workspaces:
        - name: source
        steps:
        - name: generate
          image: $(params.generator-image-url)
          workingDir: $(workspaces.source.path)
          script: |
            #!/bin/bash
            set -euxo pipefail
            export ARGO_CD_IMAGE_URL_WITH_TAG="$(params.argo-cd-url)"
            export REDIS_IMAGE_URL_WITH_TAG="$(params.redis-url)"
            export CI_ARGO_CD_UPSTREAM_COMMIT="$(params.source-commit)"
            export CI_ARGO_CD_UPSTREAM_URL="$(params.source-url)"
            pre-build-script.sh
      workspaces:
      - name: source
        workspace: source
      params:
      - name: argo-cd-url
        value: $(params.argo-cd-url)
      - name: redis-url
        value: $(params.redis-url)
      - name: source-commit
        value: $(params.source-commit)
      - name: source-url
        value: $(params.source-url)
      - name: generator-image-url
        value: $(tasks.build-spec-generator-image.results.IMAGE_URL)
    
    # TASK 4: Standart pipeline to build the RPM
    - name: build-rpm-using-konflux-standard
      runAfter: [generate-spec-file]
      taskRef:
        resolver: git
        params:
        - name: url
          value: "https://github.com/konflux-ci/rpmbuild-pipeline.git"
        - name: revision
          value: main
        - name: pathInRepo
          value: pipeline/build-rpm-package.yaml
      workspaces:
      - name: source
        workspace: source
      - name: git-auth
        workspace: git-auth
      params:
      - name: git-url
        value: $(params.git-url)
      - name: revision
        value: $(params.revision)
      # La pipeline estándar espera el nombre del paquete, no tenemos un param para él,
      # así que lo podemos hardcodear o añadir un nuevo param a nuestra pipeline.
      - name: package-name
        value: microshift-gitops
      - name: ociStorage
        value: $(params.ociStorage)
  

  params:
  - name: git-url
    value: "{{ source_url }}"
  - name: revision
    value: "{{ revision }}"
  - name: ociStorage
    value: "quay.io/redhat-user-workloads/rpm-build-pipeline-tenant/praiskup-test-package"
  - name: argo-cd-url
    value: "registry.redhat.io/openshift-gitops-1/argocd-rhel9:gitops-1.17-rhel-9-candidate"
  - name: redis-url
    value: "registry.redhat.io/rhel9/redis-6:rhel-9.3.0-container-released"
  - name: source-commit
    value: "a1b2c3d4"
  - name: source-url
    value: "https://github.com/argoproj/argo-cd"
  
  workspaces:
  - name: source
    volumeClaimTemplate:
      spec:
        accessModes: [ReadWriteOnce]
        resources: { requests: { storage: 1Gi } }
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
  
  
  
  
  
  
  
  
  
  
  
  

